$ANSIBLE_VAULT;1.1;AES256
37376563336436353265383733306534633032393837383630643361623430363631626331373636
6535393730373932616263353039643062316161316666390a633433373933313737666337396237
31396234363631363232396561303731623766626134366563363764306663393562323533363237
6632616431363666630a633063366332356634323862653737336266613566623032313666663662
31653138336332333634653566643033663831306534383235353962653264333535326131373964
63346439313866346264333561313331393634656563616534373362373830346137376463633731
32323339316437623966643362306233646331383632356433653837393266666439313831653931
33653764336130626133336563653138366434616138303138653935616562323438376436386630
38346330643133646532323734646566393835646561616363316633373262383863396137343064
64313232313165373431303065306130326239633532633466316438353966373936333535393765
37343230363535646461363836303765376263346232643632316634303963663736643265663063
31663030386433623631663134643437313062393733643631623866333131656463613136316539
3535
