dispatchers:
  hosts:
    dev1.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev2.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev3.player.eosc-data-commons.eu:
      ansible_user: ubuntu
